# Generated by Django 2.2.6 on 2019-10-02 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=5)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('avr', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('telf_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('telf_casa', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EsquemaDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EsquemaHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('sep_num', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('inicio', models.TimeField(null=True)),
                ('fin', models.TimeField(null=True)),
                ('esquema_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EsquemaHora')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=60)),
                ('avr', models.CharField(max_length=60)),
                ('u_c', models.IntegerField()),
                ('h_s', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('regimen', models.CharField(max_length=10)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('lapso_academico', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('fecha_memo', models.DateField()),
                ('observaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('pensum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pensum')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modalidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=6)),
                ('cupo', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Materia')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proyecto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turno')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pensum'),
        ),
        migrations.CreateModel(
            name='HorasTurnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hora')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turno')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.TimeField()),
                ('contrato', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('dedicacion', models.CharField(max_length=50)),
                ('observacion', models.TextField()),
                ('estatus', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='EncuentrosSeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Encuentro')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Seccion')),
            ],
        ),
        migrations.AddField(
            model_name='encuentro',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Materia'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='tipo_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoAula'),
        ),
        migrations.CreateModel(
            name='DocentesSecciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Docente')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Seccion')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estado'),
        ),
        migrations.AddField(
            model_name='docente',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_docente', to='core.Estado'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('nombre', models.IntegerField(max_length=12)),
                ('esquema_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EsquemaDia')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Direccion'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Docente'),
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aula')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dia')),
                ('encuentros_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EncuentrosSeccion')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hora')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='esquema_dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EsquemaDia'),
        ),
        migrations.AddField(
            model_name='aula',
            name='esquema_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EsquemaHora'),
        ),
        migrations.AddField(
            model_name='aula',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proyecto'),
        ),
        migrations.AddField(
            model_name='aula',
            name='tipo_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoAula'),
        ),
        migrations.AddField(
            model_name='aula',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UbicacionAula'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Docente')),
                ('encuentros_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EncuentrosSeccion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proyecto')),
            ],
        ),
    ]
