# Generated by Django 2.2.4 on 2019-11-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_memo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
