# Generated by Django 2.2.4 on 2019-11-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191103_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_memo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='lapso_academico',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
