# Generated by Django 2.2.6 on 2019-10-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191002_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
