# Generated by Django 2.2.4 on 2019-11-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191106_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='pensum',
        ),
    ]
