# Generated by Django 2.2.6 on 2019-10-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seccion_bloque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='seccion',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
