# Generated by Django 2.2.4 on 2019-11-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_proyecto_pensum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='area',
            old_name='updated',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='created',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='updated',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='created',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='updated',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='created',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='created',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='updated',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='created',
            new_name='creado',
        ),
        migrations.AddField(
            model_name='seccion',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
