# Generated by Django 2.2.4 on 2019-11-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191106_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
