# Generated by Django 2.2.6 on 2019-10-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191005_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='nombre',
            field=models.CharField(max_length=12),
        ),
    ]
