# Generated by Django 2.2.6 on 2019-10-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191005_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloque',
            name='encuentros_seccion',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='materia',
        ),
    ]
