# Generated by Django 2.2.4 on 2019-11-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='bloque',
        ),
    ]
