# Generated by Django 2.2.6 on 2019-10-05 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191005_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloque',
            name='aula',
        ),
        migrations.AddField(
            model_name='seccion',
            name='aula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Aula'),
            preserve_default=False,
        ),
    ]
