# Generated by Django 2.2.4 on 2019-11-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_seccion_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='hora_fin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Horas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccion',
            name='hora_inicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hora_inicio_bloque', to='core.Horas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccion',
            name='minutos_fin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Minutos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccion',
            name='minutos_inicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='minutos_inicio_bloque', to='core.Minutos'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BloqueHorario',
        ),
    ]
