# Generated by Django 2.2.4 on 2019-11-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_proyecto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario',
        ),
    ]
