# Generated by Django 2.2.4 on 2019-11-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_proyecto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionaula',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
