# Generated by Django 2.2.4 on 2019-11-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191106_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='hora_fin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='hora_inicio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='minutos_fin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='minutos_inicio',
            field=models.IntegerField(),
        ),
    ]
