# Generated by Django 2.2.4 on 2019-11-13 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191113_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Docente'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocentesSecciones',
        ),
    ]
