# Generated by Django 2.2.4 on 2019-11-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191116_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miercoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sabado'), ('dom', 'Domingo')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pr', 'Presencial'), ('vi', 'Virtual')], default='pr', max_length=2)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aula')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bloque')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dia')),
            ],
        ),
        migrations.CreateModel(
            name='EsquemaBloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.TimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Area')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dia')),
            ],
        ),
        migrations.CreateModel(
            name='EsquemaDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Area')),
            ],
        ),
        migrations.CreateModel(
            name='RestriccionesBloques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_rango_hora', models.TimeField(blank=True, null=True)),
                ('fin_rango_hora', models.TimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Area')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modalidad', models.CharField(choices=[('pr', 'Presencial'), ('vi', 'Virtual')], default='pr', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEncuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modalidad', models.CharField(choices=[('pr', 'Presencial'), ('vi', 'Virtual')], default='pr', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Horas',
        ),
        migrations.DeleteModel(
            name='Minutos',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='minutos_fin',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='minutos_inicio',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='turno',
        ),
        migrations.AddField(
            model_name='ubicacionaula',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Area'),
        ),
        migrations.AddField(
            model_name='esquemadia',
            name='tipo_encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoEncuentro'),
        ),
        migrations.AddField(
            model_name='esquemabloque',
            name='tipo_encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoEncuentro'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Seccion'),
        ),
        migrations.AddField(
            model_name='dia',
            name='esquema_dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EsquemaDia'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='esquema_dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EsquemaDia'),
        ),
        migrations.AddField(
            model_name='aula',
            name='tipo_aula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.TipoAula'),
            preserve_default=False,
        ),
    ]
