# Generated by Django 2.2.4 on 2019-11-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191124_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='bloque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Bloque'),
            preserve_default=False,
        ),
    ]
