# Generated by Django 2.2.4 on 2019-11-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seccion_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Turno'),
            preserve_default=False,
        ),
    ]
