# Generated by Django 2.2.4 on 2019-11-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_bloque_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='bloque',
        ),
    ]
