# Generated by Django 2.2.4 on 2019-11-24 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_seccion_bloque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_docente', to='core.Municipio'),
        ),
    ]
