# Generated by Django 2.2.4 on 2019-11-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191124_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuentro',
            name='dia',
        ),
        migrations.CreateModel(
            name='EncuentrosDias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dia')),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Encuentro')),
            ],
        ),
    ]
