# Generated by Django 2.2.4 on 2019-11-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20191124_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloque',
            name='hora_salida',
        ),
    ]
