# Generated by Django 2.2.4 on 2020-01-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('core', '0024_remove_bloque_hora_salida'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
