# Generated by Django 2.2.4 on 2020-01-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_aula_carrera'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('ubicacion', 'numero')},
        ),
    ]
