# Generated by Django 2.2.4 on 2020-01-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200117_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='numero_bloques',
            field=models.IntegerField(default=1),
        ),
    ]
