# Generated by Django 2.2.4 on 2020-01-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_encuentro_numero_bloques'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('carrera', 'nombre'), ('ubicacion', 'numero')},
        ),
    ]
