# Generated by Django 2.2.4 on 2020-01-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200119_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
